#+TITLE: Rust №15. Бесстрашная многопоточность
#+AUTHOR: Панков Михаил
#+DATE: Февраль 2017
#+EMAIL: work@michaelpankov.com
#+LANGUAGE: ru
#+CATEGORY: task
#+OPTIONS:   H:2 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+startup: beamer
#+LaTeX_CLASS: beamer
# +LaTeX_CLASS_OPTIONS: [notes]
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+latex_header: \usepackage[english,russian]{babel}
#+latex_header: \mode<beamer>{\usetheme{metropolis}}

* Обзор

** Обзор

- Как запустить несколько потоков

- Передача сообщений между потоками

- Потоки с общим состоянием

- Типажи =Sync= и =Send=

* Вступление

** Вступление

- 1:1
- M:N
- Среда исполнения

* Запуск потоков

** Запуск потоков

#+BEGIN_SRC rust
use std::thread;

fn main() {
    thread::spawn(|| {
        for i in 1..10 {
            println!("привет {} из запущенного потока!", i);
        }
    });

    for i in 1..5 {
        println!("привет {} из главного потока!", i);
    }
}
#+END_SRC

** Вывод

#+BEGIN_SRC text
привет 1 из главного потока!
привет 1 из запущенного потока!
привет 2 из главного потока!
привет 2 из запущенного потока!
привет 3 из главного потока!
привет 3 из запущенного потока!
привет 4 из главного потока!
привет 4 из запущенного потока!
привет 5 из главного потока!
привет 5 из запущенного потока!
#+END_SRC

* Ожидание завершения потоков

** join

#+BEGIN_SRC rust
  use std::thread;

  fn main() {
      let handle = thread::spawn(|| {
          for i in 1..10 {
              println!("привет {} из запущенного потока!", i);
          }
      });
      for i in 1..5 {
          println!("привет {} из главного потока!", i);
      }
      handle.join();
  }
#+END_SRC

** Вывод

#+BEGIN_SRC text
привет 1 из главного потока!
привет 1 из запущенного потока!
...
привет 6 из запущенного потока!
привет 7 из запущенного потока!
привет 8 из запущенного потока!
привет 9 из запущенного потока!
#+END_SRC

** Перемещаем join

#+BEGIN_SRC rust
use std::thread;

fn main() {
    let handle = thread::spawn(|| {
        for i in 1..10 {
            println!("привет {} из запущенного потока!", i);
        }
    });
    handle.join();
    for i in 1..5 {
        println!("привет {} из главного потока!", i);
    }
}
#+END_SRC

** Что выведется?

* Использование перемещающих замыканий

** move ||

#+BEGIN_SRC rust
use std::thread;

fn main() {
    let v = vec![1, 2, 3];

    let handle = thread::spawn(|| {
        println!("Вектор: {:?}", v);
    });

    handle.join();
}
#+END_SRC

** Ошибка

#+BEGIN_SRC text
  error[E0373]: closure may outlive the current
  function, but it borrows `v`,
  which is owned by the current function --->
  6 |     let handle = thread::spawn(|| {
    |                                ^^
    |       may outlive borrowed value `v`
  7 |         println!("Вектор: {:?}", v);
    |                                  - `v` is
    |                             borrowed here
  help: to force the closure to take ownership of
  `v` (and any other referenced
  variables), use the `move` keyword, as shown:
    |     let handle = thread::spawn(move || {
#+END_SRC

** Чтобы понять эту ошибку...

#+BEGIN_SRC rust
use std::thread;

fn main() {
    let v = vec![1, 2, 3];

    let handle = thread::spawn(|| {
        println!("Вектор: {:?}", v);
    });

    drop(v); // о нет!

    handle.join();
}
#+END_SRC

** Используем move

#+BEGIN_SRC rust
use std::thread;

fn main() {
    let v = vec![1, 2, 3];

    let handle = thread::spawn(move || {
        println!("Вектор: {:?}", v);
    });

    handle.join();
}
#+END_SRC

* Передача сообщений между потоками

** Каналы

#+BEGIN_SRC rust
use std::sync::mpsc;

fn main() {
    let (tx, rx) = mpsc::channel();
}
#+END_SRC

** Посылаем сообщение

#+BEGIN_SRC rust
use std::thread;
use std::sync::mpsc;

fn main() {
    let (tx, rx) = mpsc::channel();

    thread::spawn(move || {
        let val = String::from("привет");
        tx.send(val).unwrap();
    });
}
#+END_SRC

** Получаем сообщение

#+BEGIN_SRC rust
use std::thread;
use std::sync::mpsc;

fn main() {
    let (tx, rx) = mpsc::channel();

    thread::spawn(move || {
        let val = String::from("привет");
        tx.send(val).unwrap();
    });

    let received = rx.recv().unwrap();
    println!("Получили: {}", received);
}
#+END_SRC

** Результат

#+BEGIN_SRC text
Получили: привет
#+END_SRC

* Как каналы взаимодействуют с владением

** Пример

#+BEGIN_SRC rust
use std::thread;
use std::sync::mpsc;

fn main() {
    let (tx, rx) = mpsc::channel();
    thread::spawn(move || {
        let val = String::from("привет");
        tx.send(val).unwrap();
        println!("отправили {}", val);
    });
    let received = rx.recv().unwrap();
    println!("Получили: {}", received);
}
#+END_SRC

** Ошибка

#+BEGIN_SRC text
error[E0382]: use of moved value: `val`
  --> src/main.rs:10:31
9  |         tx.send(val).unwrap();
   |                 --- value moved here
10 |         println!("отправили {}", val);
   |                                  ^^^
   |           value used here after move
   = note: move occurs because `val` has type
   `std::string::String`, which does
   not implement the `Copy` trait
#+END_SRC

* Отправляем несколько сообщений

** Смотрим, что получатель ждёт

#+BEGIN_SRC rust
  fn main() {
      let (tx, rx) = mpsc::channel();
      thread::spawn(move || {
          let vals = vec![String::from("привет"),
            String::from("из"), String::from("потока")];
          for val in vals {
              tx.send(val).unwrap();
              thread::sleep(Duration::from_secs(1));
          }
      });
      for received in rx {
          println!("Получили: {}", received);
      }
  }
#+END_SRC

** Вывод

#+BEGIN_SRC text
Получили: привет
Получили: из
Получили: потока
#+END_SRC

* Создание нескольких источников

** Копируем передающую часть канала (1)

#+BEGIN_SRC rust
  let (tx, rx) = mpsc::channel();
  let tx1 = tx.clone();
  thread::spawn(move || {
      let vals = vec![
          String::from("привет"),
          String::from("из"),
          String::from("потока"),
      ];
      for val in vals {
          tx1.send(val).unwrap();
          thread::sleep(Duration::from_secs(1));
      }
  });
#+END_SRC

** Копируем передающую часть канала (2)

#+BEGIN_SRC rust
  thread::spawn(move || {
      let vals = vec![
          String::from("вам"),
          String::from("ещё"),
          String::from("сообщения"),
      ];
      for val in vals {
          tx.send(val).unwrap();
          thread::sleep(Duration::from_secs(1));
      }
  });

#+END_SRC

** Вывод

#+BEGIN_SRC text
Получили: привет
Получили: вам
Получили: из
Получили: ещё
Получили: потока
Получили: сообщения
#+END_SRC

* Многопоточность с общим состоянием

* Мьютексы

** API

#+BEGIN_SRC rust
use std::sync::Mutex;

fn main() {
    let m = Mutex::new(5);

    {
        let mut num = m.lock().unwrap();
        *num = 6;
    }

    println!("m = {:?}", m);
}
#+END_SRC

** Общее пользование мьютексом

#+BEGIN_SRC rust
fn main() {
    let counter = Mutex::new(0);
    let mut handles = vec![];
    for _ in 0..10 {
        let handle = thread::spawn(|| {
            let mut num = counter.lock().unwrap();
            *num += 1;
        });
        handles.push(handle);
    }
    for handle in handles { handle.join().unwrap(); }
    }
    println!("Result: {}", *counter.lock().unwrap());
}
#+END_SRC

** Не компилируется!

#+BEGIN_SRC text
error[E0373]: closure may outlive the current
function, but it borrows `counter`, which is
owned by the current function -->
9  |         let handle = thread::spawn(|| {
   may outlive borrowed value `counter` ^^
10 |             let mut num = counter.lock().unwrap();
   |`counter` is borrowed here -------
help: to force the closure to take ownership
of `counter` (and any other referenced variables),
use the `move` keyword, as shown:
   |         let handle = thread::spawn(move || {
#+END_SRC

** I like to move it

#+BEGIN_SRC rust
thread::spawn(move || {
#+END_SRC

** Опять не компилируется! (1)

#+BEGIN_SRC text
error[E0382]: capture of moved value: `counter` -->
9  |         let handle = thread::spawn(move || {
   |    value moved (into closure) here -------
10 |             let mut num = counter.lock().unwrap();
value captured here after move ^^^^^^^
   = note: move occurs because `counter` has type
  `std::sync::Mutex<i32>`,
   which does not implement the `Copy` trait
#+END_SRC

** Опять не компилируется (2)

#+BEGIN_SRC text
error[E0382]: use of moved value: `counter` -->
9  |         let handle = thread::spawn(move || {
   | value moved (into closure) here    -------
...
21 |     println!("Result: {}", *counter.lock().unwrap());
   | value used here after move  ^^^^^^^
   = note: move occurs because `counter` has
   type `std::sync::Mutex<i32>`,
   which does not implement the `Copy` trait

error: aborting due to 2 previous errors
#+END_SRC

** Упростим до 2 потоков

#+BEGIN_SRC rust
let handle = thread::spawn(move || {
    let mut num = counter.lock().unwrap();
    *num += 1;
});
handles.push(handle);
let handle2 = thread::spawn(move || {
    let mut num2 = counter.lock().unwrap();
    *num2 += 1;
});
handles.push(handle2);
#+END_SRC

** То же самое

** Множественное владение с многими потоками

#+BEGIN_SRC rust
    let counter = Rc::new(Mutex::new(0));
    let mut handles = vec![];
    for _ in 0..10 {
        let counter = counter.clone();
        let handle = thread::spawn(move || {
            let mut num = counter.lock().unwrap();
            *num += 1;
        });
        handles.push(handle);
    }
    for handle in handles { handle.join().unwrap(); }
    }
    println!("Result: {}", *counter.lock().unwrap());
#+END_SRC

** Эпизод 3: Новая ошибка

#+BEGIN_SRC text
error[E0277]: the trait bound
`std::rc::Rc<std::sync::Mutex<i32>>:
std::marker::Send` is not satisfied -->
11 |         let handle = thread::spawn(move || {
   |                      ^^^^^^^^^^^^^
   | the trait `std::marker::Send` is not
   implemented for `std::rc::Rc<std::sync::Mutex<i32>>`
   = note: `std::rc::Rc<std::sync::Mutex<i32>>`
   cannot be sent between threads safely
   = note: required because it appears within the type
   `[closure@src/main.rs:11:36: 15:10
   counter:std::rc::Rc<std::sync::Mutex<i32>>]`
   = note: required by `std::thread::spawn`
#+END_SRC

** Атомарный подсчёт ссылок с Arc<T>

#+BEGIN_SRC rust
    let counter = Arc::new(Mutex::new(0));
    let mut handles = vec![];
    for _ in 0..10 {
        let counter = counter.clone();
        let handle = thread::spawn(move || {
            let mut num = counter.lock().unwrap();
            *num += 1;
        });
        handles.push(handle);
    }
    for handle in handles { handle.join().unwrap(); }
    println!("Result: {}", *counter.lock().unwrap());
#+END_SRC

** Rust не предотвращает deadlock

Так же как и циклы ссылок

* Расширяемая многопоточность с помощью Send и Sync

** Send

- Владение значением типа можно передать в другой поток
- =Rc<T>: !Send=
- Любой тип, который состоит из значений типов =T: Send=, сам является =Send=
- Примитивные типы - =Send=

** Sync

- Безопасно ли иметь в многих потоках =&T=
- =Rc<T>: !Sync=, =RefCell<T>: !Sync=
- Любой тип, который состоит из значений типов =T: Sync=, сам является =Sync=
- Примитивные типы - =Sync=

** Реализовывать Send и Sync руками небезопасно

- Нужно когда делаешь свои структуры данных

* Домашнее задание

** Домашнее задание

- Сделать общий словарь =HashMap<u32, String>=, где номеру потока соответствует
  своё приветствие, которое он выводит на экран. Запустить 10 потоков.
- Как предыдущее, но потоки дописывают к строке свой номер.
- Взять большой текст с пробелами с множественными вхождениями определенного
  слова. Сделать так, чтобы 2 потока искали там заданное слово одновременно, а
  третий поток выводил результаты (расположение совпадения).

* Спасибо
